name: Déploiement application
on:
  workflow_dispatch:
    inputs:
      serveur:
        description: 'Environnement de déploiement'
        required: true
        default: 'dev'
jobs:
  deploy-env:
    runs-on: ubuntu-latest
    steps:
      - name: Démarage Workflow
        run: echo "Démarage du Workflow sur ${{ github.ref }}"
      - name: Checkout
        if: ${{ github.ref == 'refs/heads/main' }} 
        uses: actions/checkout@v4.1.1
      - name: Déploiement Production
        if: github.event.inputs.serveur == 'prod'
        run: echo "Déploiement en production"
