name: Déploiement application
on:
  workflow_dispatch:
    inputs:
      serveur:
        description: 'Environnement de déploiement'
        required: true
        default: 'dev'
jobs:
  deploy-env:
    runs-on: ubuntu-latest
    steps:
      - name: Démarage Workflow
        run: echo "Démarage du Workflow sur ${{ github.ref }}"
      - name: Récupération code
        run: echo "Récupération du code"
        if: ${{ github.ref == 'refs/heads/main' }} 
